"""
Hardcoded Foursquare Open Source Places category taxonomy.

Used because the source.coop release of FSQ Open Places does not ship
a separate categories file, and deriving a unique-categories table from
the 100M+ row places dataset at startup is far too slow.

This is a curated subset of the FSQ taxonomy covering the most commonly
queried categories. Each entry is a hierarchical label with " > "
separators; category_name (leaf) and category_level (depth) are derived
in load_categories().
"""

CATEGORY_LABELS = [
    # Level 1 — top-level
    "Arts and Entertainment",
    "Business and Professional Services",
    "Community and Government",
    "Dining and Drinking",
    "Event",
    "Health and Medicine",
    "Landmarks and Outdoors",
    "Retail",
    "Sports and Recreation",
    "Travel and Transportation",

    # Arts and Entertainment
    "Arts and Entertainment > Amusement Park",
    "Arts and Entertainment > Aquarium",
    "Arts and Entertainment > Art Gallery",
    "Arts and Entertainment > Bowling Alley",
    "Arts and Entertainment > Casino",
    "Arts and Entertainment > Comedy Club",
    "Arts and Entertainment > Concert Hall",
    "Arts and Entertainment > Movie Theater",
    "Arts and Entertainment > Museum",
    "Arts and Entertainment > Museum > Art Museum",
    "Arts and Entertainment > Museum > History Museum",
    "Arts and Entertainment > Museum > Science Museum",
    "Arts and Entertainment > Music Venue",
    "Arts and Entertainment > Night Club",
    "Arts and Entertainment > Performing Arts Venue",
    "Arts and Entertainment > Theater",
    "Arts and Entertainment > Zoo",

    # Business and Professional Services
    "Business and Professional Services > Advertising Agency",
    "Business and Professional Services > Architecture Firm",
    "Business and Professional Services > Construction",
    "Business and Professional Services > Consulting and Business Services",
    "Business and Professional Services > Engineering Service",
    "Business and Professional Services > Financial Service",
    "Business and Professional Services > Financial Service > Bank",
    "Business and Professional Services > Financial Service > ATM",
    "Business and Professional Services > Financial Service > Credit Union",
    "Business and Professional Services > Financial Service > Insurance Office",
    "Business and Professional Services > Financial Service > Tax Service",
    "Business and Professional Services > Funeral Services",
    "Business and Professional Services > Internet Cafe",
    "Business and Professional Services > Laundry Service",
    "Business and Professional Services > Laundry Service > Laundromat",
    "Business and Professional Services > Lawyer and Legal Services",
    "Business and Professional Services > Office",
    "Business and Professional Services > Office > Coworking Space",
    "Business and Professional Services > Real Estate Service",
    "Business and Professional Services > Recycling Facility",
    "Business and Professional Services > Salon and Barbershop",
    "Business and Professional Services > Salon and Barbershop > Hair Salon",
    "Business and Professional Services > Salon and Barbershop > Nail Salon",
    "Business and Professional Services > Spa",
    "Business and Professional Services > Storage Facility",
    "Business and Professional Services > Tailor and Alterations",
    "Business and Professional Services > Veterinarian",

    # Community and Government
    "Community and Government > City Hall",
    "Community and Government > Community Center",
    "Community and Government > Courthouse",
    "Community and Government > Education",
    "Community and Government > Education > College and University",
    "Community and Government > Education > Library",
    "Community and Government > Education > School",
    "Community and Government > Education > School > Elementary School",
    "Community and Government > Education > School > High School",
    "Community and Government > Education > School > Middle School",
    "Community and Government > Embassy and Consulate",
    "Community and Government > Fire Station",
    "Community and Government > Government Building",
    "Community and Government > Place of Worship",
    "Community and Government > Place of Worship > Buddhist Temple",
    "Community and Government > Place of Worship > Church",
    "Community and Government > Place of Worship > Hindu Temple",
    "Community and Government > Place of Worship > Mosque",
    "Community and Government > Place of Worship > Synagogue",
    "Community and Government > Police Station",
    "Community and Government > Post Office",
    "Community and Government > Prison",

    # Dining and Drinking
    "Dining and Drinking > Bar",
    "Dining and Drinking > Bar > Beer Bar",
    "Dining and Drinking > Bar > Cocktail Bar",
    "Dining and Drinking > Bar > Hotel Bar",
    "Dining and Drinking > Bar > Pub",
    "Dining and Drinking > Bar > Sports Bar",
    "Dining and Drinking > Bar > Wine Bar",
    "Dining and Drinking > Brewery",
    "Dining and Drinking > Cafe, Coffee, and Tea House",
    "Dining and Drinking > Cafe, Coffee, and Tea House > Cafe",
    "Dining and Drinking > Cafe, Coffee, and Tea House > Coffee Shop",
    "Dining and Drinking > Cafe, Coffee, and Tea House > Tea Room",
    "Dining and Drinking > Cafeteria",
    "Dining and Drinking > Dessert Shop",
    "Dining and Drinking > Dessert Shop > Bakery",
    "Dining and Drinking > Dessert Shop > Donut Shop",
    "Dining and Drinking > Dessert Shop > Ice Cream Parlor",
    "Dining and Drinking > Distillery",
    "Dining and Drinking > Food Court",
    "Dining and Drinking > Food Truck",
    "Dining and Drinking > Restaurant",
    "Dining and Drinking > Restaurant > American Restaurant",
    "Dining and Drinking > Restaurant > Asian Restaurant",
    "Dining and Drinking > Restaurant > Asian Restaurant > Chinese Restaurant",
    "Dining and Drinking > Restaurant > Asian Restaurant > Indian Restaurant",
    "Dining and Drinking > Restaurant > Asian Restaurant > Japanese Restaurant",
    "Dining and Drinking > Restaurant > Asian Restaurant > Japanese Restaurant > Sushi Restaurant",
    "Dining and Drinking > Restaurant > Asian Restaurant > Korean Restaurant",
    "Dining and Drinking > Restaurant > Asian Restaurant > Thai Restaurant",
    "Dining and Drinking > Restaurant > Asian Restaurant > Vietnamese Restaurant",
    "Dining and Drinking > Restaurant > BBQ Joint",
    "Dining and Drinking > Restaurant > Breakfast Spot",
    "Dining and Drinking > Restaurant > Burger Joint",
    "Dining and Drinking > Restaurant > Diner",
    "Dining and Drinking > Restaurant > Fast Food Restaurant",
    "Dining and Drinking > Restaurant > French Restaurant",
    "Dining and Drinking > Restaurant > Greek Restaurant",
    "Dining and Drinking > Restaurant > Italian Restaurant",
    "Dining and Drinking > Restaurant > Italian Restaurant > Pizza Place",
    "Dining and Drinking > Restaurant > Mediterranean Restaurant",
    "Dining and Drinking > Restaurant > Mexican Restaurant",
    "Dining and Drinking > Restaurant > Mexican Restaurant > Taco Place",
    "Dining and Drinking > Restaurant > Middle Eastern Restaurant",
    "Dining and Drinking > Restaurant > Sandwich Spot",
    "Dining and Drinking > Restaurant > Seafood Restaurant",
    "Dining and Drinking > Restaurant > Spanish Restaurant",
    "Dining and Drinking > Restaurant > Steakhouse",
    "Dining and Drinking > Restaurant > Vegetarian and Vegan Restaurant",
    "Dining and Drinking > Smoothie and Juice Bar",
    "Dining and Drinking > Snack Place",
    "Dining and Drinking > Winery",

    # Event
    "Event > Conference",
    "Event > Festival",
    "Event > Marathon",
    "Event > Trade Fair",

    # Health and Medicine
    "Health and Medicine > Acupuncture Clinic",
    "Health and Medicine > Alternative Medicine Clinic",
    "Health and Medicine > Blood Bank",
    "Health and Medicine > Chiropractor",
    "Health and Medicine > Dentist",
    "Health and Medicine > Doctor",
    "Health and Medicine > Doctor > Dermatologist",
    "Health and Medicine > Doctor > Pediatrician",
    "Health and Medicine > Emergency Service",
    "Health and Medicine > Emergency Service > Urgent Care Center",
    "Health and Medicine > Eye Doctor and Optometrist",
    "Health and Medicine > Hospital",
    "Health and Medicine > Medical Center",
    "Health and Medicine > Medical Lab",
    "Health and Medicine > Mental Health Service",
    "Health and Medicine > Nursing Home",
    "Health and Medicine > Pharmacy",
    "Health and Medicine > Physical Therapy Clinic",

    # Landmarks and Outdoors
    "Landmarks and Outdoors > Beach",
    "Landmarks and Outdoors > Bridge",
    "Landmarks and Outdoors > Cemetery",
    "Landmarks and Outdoors > Garden",
    "Landmarks and Outdoors > Harbor or Marina",
    "Landmarks and Outdoors > Historic and Protected Site",
    "Landmarks and Outdoors > Lake",
    "Landmarks and Outdoors > Monument",
    "Landmarks and Outdoors > Mountain",
    "Landmarks and Outdoors > Park",
    "Landmarks and Outdoors > Park > Dog Park",
    "Landmarks and Outdoors > Park > National Park",
    "Landmarks and Outdoors > Park > Playground",
    "Landmarks and Outdoors > Park > State Park",
    "Landmarks and Outdoors > Plaza",
    "Landmarks and Outdoors > Scenic Lookout",
    "Landmarks and Outdoors > Trail",
    "Landmarks and Outdoors > Waterfall",

    # Retail
    "Retail > Antique Store",
    "Retail > Arts and Crafts Store",
    "Retail > Auto Dealership",
    "Retail > Automotive Repair Shop",
    "Retail > Bicycle Store",
    "Retail > Bookstore",
    "Retail > Camera Store",
    "Retail > Clothing Store",
    "Retail > Clothing Store > Boutique",
    "Retail > Clothing Store > Lingerie Store",
    "Retail > Clothing Store > Shoe Store",
    "Retail > Computers and Electronics Retail",
    "Retail > Convenience Store",
    "Retail > Cosmetics Store",
    "Retail > Department Store",
    "Retail > Discount Store",
    "Retail > Florist",
    "Retail > Furniture and Home Store",
    "Retail > Furniture and Home Store > Hardware Store",
    "Retail > Gift Store",
    "Retail > Grocery Store",
    "Retail > Grocery Store > Supermarket",
    "Retail > Hobby Store",
    "Retail > Jewelry Store",
    "Retail > Liquor Store",
    "Retail > Luggage Store",
    "Retail > Mall",
    "Retail > Mall > Shopping Mall",
    "Retail > Market",
    "Retail > Market > Farmers Market",
    "Retail > Mobile Phone Store",
    "Retail > Music Store",
    "Retail > Newsstand",
    "Retail > Pet Store",
    "Retail > Smoke Shop",
    "Retail > Sporting Goods Retail",
    "Retail > Toy Store",
    "Retail > Video Game Store",
    "Retail > Warehouse Store",

    # Sports and Recreation
    "Sports and Recreation > Athletics and Sports",
    "Sports and Recreation > Athletics and Sports > Basketball Court",
    "Sports and Recreation > Athletics and Sports > Golf Course",
    "Sports and Recreation > Athletics and Sports > Gym and Studio",
    "Sports and Recreation > Athletics and Sports > Gym and Studio > Gym",
    "Sports and Recreation > Athletics and Sports > Gym and Studio > Yoga Studio",
    "Sports and Recreation > Athletics and Sports > Soccer Field",
    "Sports and Recreation > Athletics and Sports > Tennis Court",
    "Sports and Recreation > Climbing Gym",
    "Sports and Recreation > Pool and Billiards",
    "Sports and Recreation > Race Track",
    "Sports and Recreation > Skating Rink",
    "Sports and Recreation > Ski Area",
    "Sports and Recreation > Stadium",
    "Sports and Recreation > Stadium > Baseball Stadium",
    "Sports and Recreation > Stadium > Basketball Stadium",
    "Sports and Recreation > Stadium > Football Stadium",
    "Sports and Recreation > Stadium > Soccer Stadium",
    "Sports and Recreation > Swimming Pool",

    # Travel and Transportation
    "Travel and Transportation > Airport",
    "Travel and Transportation > Bike Rental",
    "Travel and Transportation > Border Crossing",
    "Travel and Transportation > Bus Station",
    "Travel and Transportation > Bus Stop",
    "Travel and Transportation > Car Rental",
    "Travel and Transportation > Charging Station",
    "Travel and Transportation > Cruise",
    "Travel and Transportation > Ferry",
    "Travel and Transportation > Gas Station",
    "Travel and Transportation > Heliport",
    "Travel and Transportation > Lodging",
    "Travel and Transportation > Lodging > Bed and Breakfast",
    "Travel and Transportation > Lodging > Hostel",
    "Travel and Transportation > Lodging > Hotel",
    "Travel and Transportation > Lodging > Motel",
    "Travel and Transportation > Lodging > Resort",
    "Travel and Transportation > Lodging > Vacation Rental",
    "Travel and Transportation > Parking",
    "Travel and Transportation > Pier",
    "Travel and Transportation > Port",
    "Travel and Transportation > Rest Area",
    "Travel and Transportation > Road",
    "Travel and Transportation > Taxi",
    "Travel and Transportation > Train Station",
    "Travel and Transportation > Transport Hub",
    "Travel and Transportation > Travel Agency",
    "Travel and Transportation > Tunnel",
]
